version: "3"
services: #global value
    database:
        image: mysql:5.5
        volumes: 
            - ./data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpressuser
            MYSQL_PASSWORD: wordpress
    wordpress: 
        image: wordpress
        depends_on: 
            - database
        ports: 
            - "9090:80"
        restart: always
        volumes:
            - ./src:/var/www/html
        environment: 
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: wordpressuser
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        

